# Generated by Django 4.2.1 on 2023-09-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examiner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_date_limit',
            field=models.BooleanField(default=False),
        ),
    ]
