# Generated by Django 4.2.1 on 2023-09-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examiner', '0002_exam_is_date_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_language',
            field=models.JSONField(default=['JAVASCRIPT_NODE', 'PYTHON3', 'PHP', 'JAVA14', 'TYPESCRIPT', 'CPP17', 'RUBY', 'C']),
        ),
    ]
