# Generated by Django 4.2.1 on 2023-09-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examiner', '0003_exam_exam_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='allow_redo_exam',
            field=models.BooleanField(default=False),
        ),
    ]
