# Generated by Django 4.1.6 on 2023-04-25 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendexam',
            name='video',
            field=models.FileField(blank=True, default=None, null=True, upload_to='attendee_videos/'),
        ),
    ]
