# Generated by Django 4.1.6 on 2023-04-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0002_alter_attendexam_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendquestion',
            name='number',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
        ),
    ]
