# Generated by Django 4.1.6 on 2023-04-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0003_alter_attendquestion_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendquestion',
            name='javascript_code',
            field=models.TextField(blank=True, default=None, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='attendquestion',
            name='python_code',
            field=models.TextField(blank=True, default=None, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='attendquestion',
            name='answer',
            field=models.TextField(blank=True, default=None, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='attendquestion',
            name='language',
            field=models.CharField(choices=[('JAVASCRIPT_NODE', 'JAVASCRIPT_NODE'), ('PYTHON3', 'PYTHON3')], default='PYTHON3', max_length=20),
        ),
    ]
