# Generated by Django 4.1.6 on 2023-04-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0004_attendquestion_javascript_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendexam',
            name='status',
            field=models.CharField(default='In Progress', max_length=20),
        ),
    ]
