# Generated by Django 4.2.1 on 2023-09-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0006_rename_total_cheat_attendexam_copy_detect_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendquestion',
            name='code_snippets',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='attendquestion',
            name='language',
            field=models.CharField(choices=[('JAVASCRIPT_NODE', 'JAVASCRIPT_NODE'), ('PYTHON3', 'PYTHON3'), ('PHP', 'PHP'), ('JAVA14', 'JAVA14'), ('TYPESCRIPT', 'TYPESCRIPT'), ('CPP17', 'CPP17'), ('RUBY', 'RUBY'), ('C', 'C')], default='JAVASCRIPT_NODE', max_length=20),
        ),
    ]
