# Generated by Django 4.2.1 on 2023-09-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0007_attendquestion_code_snippets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendexam',
            name='retake_exam',
            field=models.BooleanField(default=False),
        ),
    ]
