# Generated by Django 4.1.6 on 2023-04-25 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(default=None, max_length=100)),
                ('description', models.TextField(blank=True, default=None, max_length=5000, null=True)),
                ('example', models.TextField(blank=True, default=None, max_length=500, null=True)),
                ('level', models.CharField(choices=[('Easy', 'easy'), ('Medium', 'medium'), ('Hard', 'hard')], default='Easy', max_length=10)),
                ('init_code', models.TextField(blank=True, default=None, max_length=5000, null=True)),
                ('is_private', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_updated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('everything', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Testcase',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('number', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1)),
                ('input', models.TextField(blank=True, default=None, max_length=500, null=True)),
                ('output', models.TextField(blank=True, default=None, max_length=500, null=True)),
                ('is_private', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_updated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='author.question')),
            ],
            options={
                'ordering': ('-question', 'number'),
                'unique_together': {('question', 'number')},
            },
            managers=[
                ('everything', django.db.models.manager.Manager()),
            ],
        ),
    ]
