# Generated by Django 4.1.6 on 2023-04-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_alter_testcase_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='init_code',
            new_name='javascript_init_code',
        ),
        migrations.AddField(
            model_name='question',
            name='python_init_code',
            field=models.TextField(blank=True, default=None, max_length=5000, null=True),
        ),
    ]
