# Generated by Django 4.2.1 on 2023-09-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_rename_init_code_question_javascript_init_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='exam_language',
            field=models.JSONField(default=['python', 'javascript', 'php', 'java', 'typescript', 'cpp', 'ruby', 'c']),
        ),
    ]
