# Generated by Django 4.2.1 on 2023-09-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0004_question_exam_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='exam_language',
            field=models.JSONField(default=['JAVASCRIPT_NODE', 'PYTHON3', 'PHP', 'JAVA14', 'TYPESCRIPT', 'CPP17', 'RUBY', 'C']),
        ),
    ]
