# Generated by Django 4.2.1 on 2023-09-15 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0005_alter_question_exam_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='exam_language',
        ),
    ]
