# Generated by Django 4.2.1 on 2023-09-26 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0007_question_exam_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='exam_language',
            new_name='question_language',
        ),
    ]
